/**
 * Worktree data is generated by the local /sync-dashboard Claude command and
 * committed to this repo. The dashboard reads it as a static asset — no token
 * required, no API call to a third party.
 */

export interface WorktreeGitState {
  staged: number;
  modified: number;
  untracked: number;
  ahead: number;
  behind: number;
}

export interface Worktree {
  ticket: string;
  title: string | null;
  status: string | null;
  next_action: string | null;
  branch: string;
  github_repo: string | null;
  pr_url: string | null;
  review_status: string | null;
  git: WorktreeGitState;
  last_activity: string | null;
}

export interface PluginWorktrees {
  name: string;
  worktrees: Worktree[];
}

export interface WorktreeData {
  generated_at: string;
  plugins: PluginWorktrees[];
}

export async function fetchWorktreeData(): Promise<WorktreeData | null> {
  const url = `${import.meta.env.BASE_URL}worktree-data.json`;
  const res = await fetch(url, { cache: 'no-cache' });
  if (!res.ok) {
    if (res.status === 404) return null;
    throw new Error(`Failed to load worktree data: ${res.status}`);
  }
  return res.json();
}

export function summariseGit(git: WorktreeGitState): string {
  const parts: string[] = [];
  if (git.staged > 0) parts.push(`S:${git.staged}`);
  if (git.modified > 0) parts.push(`M:${git.modified}`);
  if (git.untracked > 0) parts.push(`U:${git.untracked}`);
  return parts.length === 0 ? 'clean' : parts.join(' ');
}
